/* M1 validation: run the g4 f32 forward pass on the toy GGUF generated by
 * the real Gemma 4 JAX modules (gemma fork, g4ref/gen_toy_vectors.py) and
 * compare the per-position logits. */

#include "../g4.h"
#include "../g4_gguf.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv) {
    /* argv: [model.gguf [ref.gguf [max_abs_diff]]] — the ref defaults to the
     * model file itself (toy.gguf carries its own ref.* tensors); a converted
     * GGUF is validated against toy.gguf's references. */
    const char *path = argc > 1 ? argv[1] : "tests/vectors/toy.gguf";
    const char *ref_path = argc > 2 ? argv[2] : path;
    double max_allowed = argc > 3 ? atof(argv[3]) : 5e-3;
    char err[256] = "";

    g4_gguf g;
    if (g4_gguf_open(&g, ref_path, err, sizeof(err))) {
        fprintf(stderr, "cannot open %s: %s\n", ref_path, err);
        return 1;
    }
    const g4_gguf_tensor *ttok = g4_gguf_tensor_by_name(&g, "ref.tokens");
    const g4_gguf_tensor *tlog = g4_gguf_tensor_by_name(&g, "ref.logits");
    if (!ttok || !tlog) {
        fprintf(stderr, "reference tensors missing\n");
        return 1;
    }
    uint32_t n_tokens = (uint32_t)ttok->dims[0];
    uint32_t vocab = (uint32_t)tlog->dims[0];
    int32_t *tokens = malloc(sizeof(int32_t) * n_tokens);
    float *ref = malloc(sizeof(float) * (size_t)n_tokens * vocab);
    if (g4_gguf_read_tensor_data(&g, ttok, tokens) ||
        g4_gguf_read_tensor_data(&g, tlog, ref))
    {
        fprintf(stderr, "cannot read reference tensors\n");
        return 1;
    }
    g4_gguf_close(&g);

    g4_model *m = g4_model_load(path, err, sizeof(err));
    if (!m) {
        fprintf(stderr, "model load failed: %s\n", err);
        return 1;
    }
    if (g4_model_vocab(m) != vocab) {
        fprintf(stderr, "vocab mismatch\n");
        return 1;
    }

    float *logits = malloc(sizeof(float) * (size_t)n_tokens * vocab);
    if (g4_forward_prefill_f32(m, tokens, n_tokens, logits)) {
        fprintf(stderr, "forward failed\n");
        return 1;
    }

    double max_abs = 0.0, sum_abs = 0.0;
    uint32_t max_pos = 0, argmax_match = 0;
    for (uint32_t p = 0; p < n_tokens; p++) {
        uint32_t am_ref = 0, am_got = 0;
        for (uint32_t v = 0; v < vocab; v++) {
            size_t i = (size_t)p * vocab + v;
            double d = fabs((double)logits[i] - (double)ref[i]);
            sum_abs += d;
            if (d > max_abs) { max_abs = d; max_pos = p; }
            if (ref[i] > ref[(size_t)p * vocab + am_ref]) am_ref = v;
            if (logits[i] > logits[(size_t)p * vocab + am_got]) am_got = v;
        }
        if (am_ref == am_got) argmax_match++;
    }
    double mean_abs = sum_abs / ((double)n_tokens * vocab);
    printf("toy forward: %u tokens, vocab %u\n", n_tokens, vocab);
    printf("  max |diff| %.3e (pos %u), mean |diff| %.3e, argmax match %u/%u\n",
           max_abs, max_pos, mean_abs, argmax_match, n_tokens);

    int failed = 0;
    if (max_abs > max_allowed || mean_abs > max_allowed / 10.0 ||
        argmax_match != n_tokens) {
        printf("FAILED: logits diverge from the JAX reference\n");
        failed = 1;
    } else {
        printf("OK: g4 forward matches the JAX reference\n");
    }

    g4_model_free(m);
    free(tokens);
    free(ref);
    free(logits);
    return failed;
}
